name: wb idkt stocks

on:
    push:


env:
    Azarya: ${{ secrets.AZARYA }}
    Michael:  ${{ secrets.MICHAEL }}
    Rachel:  ${{ secrets.RACHEL }}
    Galilova:  ${{ secrets.GALILOVA }}
    TORGMAKSIMUM:  ${{ secrets.TORGMAKSIMUM }}
    Martynenko:  ${{ secrets.MARTYNENKO }}
    Sergey:  ${{ secrets.SERGEY }}



jobs:
    idkt-Run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies # workflow update to trigger action
              run: pip install -r requirements.txt
            - name: Write Google Service Account Key
              run: echo "${{ secrets.GOOGLE_SHEETS }}" > key.json
            - name: Run iidkt
              run: python iidkt.py
        
