name: wb idkt stocks

on:
    push:

jobs:
    idkt-Run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies # workflow update to trigger action
              run: pip install -r requirements.txt
            - name: Run iidkt
              run: python iidkt.py
              