name: Run wb and oz Stocks

on:
  schedule:
    - cron: '0 2 * * *'  # Ежедневно в 5:00 по МСК (UTC+3)
  workflow_dispatch:

env:
  Azarya: ${{ secrets.AZARYA }}
  Michael: ${{ secrets.MICHAEL }}
  Rachel: ${{ secrets.RACHEL }}
  Galilova: ${{ secrets.GALILOVA }}
  Martynenko: ${{ secrets.MARTYNENKO }}
  Melikhov: ${{ secrets.Melikhov }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  MY_TG_CHAT_ID: ${{ secrets.MY_TG_CHAT_ID }}

  HAVVA_Client_id_oz: ${{ secrets.HAVVA_Client_id_oz }}
  HAVVA_api_key_oz: ${{ secrets.HAVVA_api_key_oz }}

  Gabriel_Client_id_oz: ${{ secrets.Gabriel_Client_id_oz }}
  Gabriel_api_key_oz: ${{ secrets.Gabriel_api_key_oz }}

  UCARE_Client_id_oz: ${{ secrets.UCARE_Client_id_oz }}
  UCARE_api_key_oz: ${{ secrets.UCARE_api_key_oz }}


jobs:
  Stocks-Run-wb-and-oz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

     

      - name: Decode Google Service Account Key
        run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json

      - name: Run WB Supplier Stocks
        run: python -m scripts.pipelines.get_supplier_stocks

      - name: Run OZ Supplier Stocks
        run: python -m scripts.pipelines_oz.get_stocks_oz

