name: wb idkt stocks

on:
    schedule:
        - cron: '0 * * * *'


env:
    Azarya: ${{ secrets.AZARYA }}
    Michael: ${{ secrets.MICHAEL }}
    Rachel: ${{ secrets.RACHEL }}
    Galilova: ${{ secrets.GALILOVA }}
    TORGMAKSIMUM: ${{ secrets.TORGMAKSIMUM }}
    Martynenko: ${{ secrets.MARTYNENKO }}
    Sergey: ${{ secrets.SERGEY }}

# проверка

jobs:
    idkt-Run:
        runs-on: ubuntu-latest
        permissions:
           contents: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name:  Create data directory
              run: mkdir -p data
            - name: Debug - Workflow started
              run: echo "Workflow started at $(date)"
            - name: Install Dependencies # workflow update to trigger action
              run: pip install -r requirements.txt
            - name:  Decode Google Service Account Key (from base64)
              run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json
            - name: Run iidkt
              run: python scripts/iidkt.py
            - name: Debug - Check generated files
              run: |
                git config --global user.name "GitHub Actions"
                git config -- global.email "actions@github.com"
                git add data/
                git commit -m "Auto-update: IDKT CSV files [$(date +'%Y-%m-%d %H:%M')]"
                git pull --rebase  # Избегаем конфликтов
                git push
            - name: Upload CSV as artifact (optional)
              uses: actions/upload-artifact@v4
              with:
                name: idkt-csv
                path: data/IDKT-*.csv
                retention-days: 3