name: Run transfer from AM in AM OZ

on:
  schedule:
    - cron: '0 4 * * *'  # Ежедневно в 7:00 МСК (UTC+3)
  workflow_dispatch:

jobs:
  transfer-wb-oz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Decode Google Service Account Key
      run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json

    - name: Run Transfer Script
      run: python -m scripts.price_transfer_in_oz
