name: Weekly Salles + Advert + Galilova (Mon 7am)


on:
    schedule:
        - cron: '0 3 * * 1'
    workflow_dispatch:

env:
    Azarya: ${{ secrets.AZARYA }}
    Michael:  ${{ secrets.MICHAEL }}
    Rachel:  ${{ secrets.RACHEL }}
    Galilova:  ${{ secrets.GALILOVA }}
    Martynenko:  ${{ secrets.MARTYNENKO }}
    TG_TOKEN: ${{ secrets.TG_TOKEN }}
    MY_TG_CHAT_ID: ${{ secrets.MY_TG_CHAT_ID }}

# проверка

jobs:
    sales-job:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name:  Create data directory
              run: mkdir -p data

            - name: Debug - Workflow started
              run: echo "Workflow started at $(date)"

            - name: Install Dependencies # workflow update to trigger action
              run: pip install -r requirements.txt

            - name:  Decode Google Service Account Key (from base64)
              run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json

            - name: Run Salles funnel
              run: python -m scripts/get_sales_funnel.py

            - name: Commit cache updates (if any)
              run: |
                git config --global user.email "bot@github.com"
                git config --global user.name "GitHub Actions Bot"
                git add cache/*.pkl
                git commit -m "♻️ update IDKT cache (auto)" || echo "No changes to commit"
                git push
     
    advertising-job:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name:  Create data directory
              run: mkdir -p data

            - name: Debug - Workflow started
              run: echo "Workflow started at $(date)"

            - name: Install Dependencies # workflow update to trigger action
              run: pip install -r requirements.txt
              
            - name:  Decode Google Service Account Key (from base64)
              run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json

            - name: Run Advertising Campaign
              run: python scripts/get_advertising_report.py

            - name: Commit cache updates (if any)
              run: |
                git config --global user.email "bot@github.com"
                git config --global user.name "GitHub Actions Bot"
                git add cache/*.pkl
                git commit -m "♻️ update IDKT cache (auto)" || echo "No changes to commit"
                git push

    Galilova-job:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name:  Create data directory
              run: mkdir -p data

            - name: Debug - Workflow started
              run: echo "Workflow started at $(date)"

            - name: Install Dependencies # workflow update to trigger action
              run: pip install -r requirements.txt

            - name:  Decode Google Service Account Key (from base64)
              run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json

            - name: Run Advertising Galilova Campaign
              run: python scripts/Galilova-advertising.py

