# name: Salles Funnel run every Monday at 7 am

# on:
#     schedule:
#         - cron: '0 7 * * 1'


# env:
#     Azarya: {{ secrets.AZARYA }}
#     Michael: {{ secrets.MICHAEL }}
#     Rachel: {{ secrets.RACHEL }}
#     Galilova: {{ secrets.GALILOVA }}
#     TORGMAKSIMUM: {{ secrets.TORGMAKSIMUM }}
#     Martynenko: {{ secrets.MARTYNENKO }}
#     Sergey: {{ secrets.SERGEY }}

# # проверка

# jobs:
#     salles-job:
    
#         Salles-Run:
#             runs-on: ubuntu-latest
#             steps:
#                 - name: Checkout Code
#                   uses: actions/checkout@v4
#                 - name: Set up Python
#                   uses: actions/setup-python@v4
#                   with:
#                   python-version: '3.10'
#                 - name:  Create data directory
#                   run: mkdir -p data
#                 - name: Debug - Workflow started
#                   run: echo "Workflow started at $(date)"
#                 - name: Install Dependencies # workflow update to trigger action
#                   run: pip install -r requirements.txt
#                 - name:  Decode Google Service Account Key (from base64)
#                   run: echo "{{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json
#                 - name: Run Salles funnel
#                   run: python scripts/salles-funnel.py
     
#     advertising-job:
#         advertising-Run:

