name: WB Directory


on:
    push:
    schedule:
        - cron: '0 * * * *'


jobs:
    Run-WB-Directory:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies # workflow update to trigger action
              run: pip install -r requirements.txt
            - name:  Decode Google Service Account Key (from base64)
              run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json
            - name: Run directory_wb
              run: python scripts/directory_wb.py