name: WB Directory and OZ Directory and MyWarehouse and price transfer_am_in_oz integrations

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

env:
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  MY_TG_CHAT_ID: ${{ secrets.MY_TG_CHAT_ID }}

jobs:
  Run-WB-OZ-Directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Decode Google Service Account Key (from base64)
        run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 -d > key.json

      - name: Debug directory (временно)
        run: |
          pwd
          ls -la
          ls -la scripts

      - name: Run directory_wb_oz
        run: python -m scripts.integrations.directory_wb_and_oz

      - name: Run mywerehouse in cabinet table
        run: python -m scripts.integrations.split_and_upload_myWarehouse_sheets

      - name: Run Transfer Script
        run: python -m scripts.integrations.price_transfer_in_oz